name: TMD
channels:
  - conda-forge
dependencies:
  - jupyter
  - numpy==1.26.4
  - matplotlib==3.8.3
  - pip
  - scipy==1.12.0
  - python >=3.9
  - pandas==2.2.1
  - seaborn==0.13.2
  - lmfit==1.2.2
  - peakutils==1.3.4
  - openpyxl==3.1.2
  - pip:
      - joblib==1.3.2
      - scikit-learn==1.4.0
      - threadpoolctl==3.3.0
