name: TMD
channels:
  - conda-forge
dependencies:
  - jupyter
  - numpy
  - matplotlib
  - pip
  - scipy
  - python >=3.9
  - pandas
  - seaborn
  - pip:
      - joblib==1.3.2
      - scikit-learn==1.4.0
      - threadpoolctl==3.3.0
